[0m12:25:04.542431 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fad40d578c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fad3fd7bed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fad3fd7b9d0>]}


============================== 12:25:04.547292 | 55cf053d-968a-4074-97c5-e7d312f9d0c9 ==============================
[0m12:25:04.547292 [info ] [MainThread]: Running with dbt=1.10.7
[0m12:25:04.548205 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/chinaemerem/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:25:24.518598 [debug] [MainThread]: Starter project path: /export/data0/chinaemerem/prac_dbt_synthea/env/lib/python3.13/site-packages/dbt/include/starter_project
[0m12:25:24.524518 [info ] [MainThread]: 
Your new dbt project "prac_dbt_synthea" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:25:24.525446 [info ] [MainThread]: Setting up your profile.
[0m12:28:23.445440 [info ] [MainThread]: Profile prac_dbt_synthea written to /home/chinaemerem/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m12:28:23.447651 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 199.00287, "process_in_blocks": "0", "process_kernel_time": 0.211848, "process_mem_max_rss": "105452", "process_out_blocks": "112", "process_user_time": 2.254389}
[0m12:28:23.448810 [debug] [MainThread]: Command `dbt init` succeeded at 12:28:23.448583 after 199.00 seconds
[0m12:28:23.449720 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fad3fe17100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fad40b3cdd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fad3fe1dbf0>]}
[0m12:28:23.450395 [debug] [MainThread]: Flushing usage events
[0m12:28:23.864171 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:28:39.461435 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fef2578c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fee27bed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fee27b9d0>]}


============================== 12:28:39.466697 | dd0b243e-91a0-4690-a757-38af7fd4b937 ==============================
[0m12:28:39.466697 [info ] [MainThread]: Running with dbt=1.10.7
[0m12:28:39.467649 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/chinaemerem/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:28:39.482630 [info ] [MainThread]: dbt version: 1.10.7
[0m12:28:39.483357 [info ] [MainThread]: python version: 3.13.2
[0m12:28:39.484178 [info ] [MainThread]: python path: /export/data0/chinaemerem/prac_dbt_synthea/env/bin/python
[0m12:28:39.484764 [info ] [MainThread]: os info: Linux-6.4.0-150600.23.60-default-x86_64-with-glibc2.38
[0m12:28:39.570842 [info ] [MainThread]: Using profiles dir at /home/chinaemerem/.dbt
[0m12:28:39.571544 [info ] [MainThread]: Using profiles.yml file at /home/chinaemerem/.dbt/profiles.yml
[0m12:28:39.572113 [info ] [MainThread]: Using dbt_project.yml file at /export/data0/chinaemerem/prac_dbt_synthea/dbt_project.yml
[0m12:28:39.572798 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m12:28:39.574195 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.2230017, "process_in_blocks": "0", "process_kernel_time": 0.211774, "process_mem_max_rss": "105744", "process_out_blocks": "16", "process_user_time": 2.417424}
[0m12:28:39.574935 [debug] [MainThread]: Command `dbt debug` failed at 12:28:39.574771 after 0.22 seconds
[0m12:28:39.575542 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fee31bce0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fee222450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fee3269c0>]}
[0m12:28:39.576195 [debug] [MainThread]: Flushing usage events
[0m12:28:40.260314 [debug] [MainThread]: An error was encountered while trying to flush usage events
